// <auto-generated />
using System;
using ConstructionCompanyDataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConstructionCompanyDataLayer.Migrations
{
    [DbContext(typeof(ConstructionCompanyContext))]
    partial class ConstructionCompanyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.ConstructionSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int>("CreatedById");

                    b.Property<DateTime?>("DateFinish");

                    b.Property<DateTime?>("DateStart");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("OpenStatus");

                    b.Property<decimal>("ProjectWorth");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("ConstructionSites");
                });

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.ConstructionSiteManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ConstructionSiteManagers");
                });

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.ConstructionSiteSiteManager", b =>
                {
                    b.Property<int>("ConstructionSiteId");

                    b.Property<int>("ConstructionSiteManagerId");

                    b.HasKey("ConstructionSiteId", "ConstructionSiteManagerId");

                    b.HasIndex("ConstructionSiteManagerId");

                    b.ToTable("ConstructionSiteSiteManager");
                });

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime?>("PurchaseDate");

                    b.Property<int>("Quantity");

                    b.Property<string>("SerialNumber");

                    b.HasKey("Id");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Manager");
                });

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Unit");

                    b.HasKey("Id");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("Name");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title");

                    b.Property<int>("WorksheetId");

                    b.HasKey("Id");

                    b.HasIndex("WorksheetId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName");

                    b.Property<bool>("NeedToChangePassword");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PasswordSalt");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.UserRole", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("JobDescription");

                    b.Property<string>("TelephoneNumber");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.WorkerTask", b =>
                {
                    b.Property<int>("WorkerId");

                    b.Property<int>("TaskId");

                    b.Property<string>("WorkDescription");

                    b.HasKey("WorkerId", "TaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("WorkerTask");
                });

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.Worksheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConstructionSiteId");

                    b.Property<int?>("ConstructionSiteManagerId");

                    b.Property<DateTime>("Date");

                    b.Property<bool>("IsLocked");

                    b.Property<string>("Remarks");

                    b.Property<string>("WeatherConditions");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionSiteId");

                    b.HasIndex("ConstructionSiteManagerId");

                    b.ToTable("Worksheets");
                });

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.WorksheetEquipment", b =>
                {
                    b.Property<int>("WorksheetId");

                    b.Property<int>("EquipmentId");

                    b.Property<int>("Amount");

                    b.Property<DateTime>("UsageEnd");

                    b.Property<DateTime>("UsageStart");

                    b.HasKey("WorksheetId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("WorksheetEquipment");
                });

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.WorksheetMaterial", b =>
                {
                    b.Property<int>("WorksheetId");

                    b.Property<int>("MaterialId");

                    b.Property<double>("Amount");

                    b.HasKey("WorksheetId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("WorksheetMaterial");
                });

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.ConstructionSite", b =>
                {
                    b.HasOne("ConstructionCompanyDataLayer.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.ConstructionSiteManager", b =>
                {
                    b.HasOne("ConstructionCompanyDataLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.ConstructionSiteSiteManager", b =>
                {
                    b.HasOne("ConstructionCompanyDataLayer.Models.ConstructionSite", "ConstructionSite")
                        .WithMany("ConstructionSiteManagers")
                        .HasForeignKey("ConstructionSiteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ConstructionCompanyDataLayer.Models.ConstructionSiteManager", "ConstructionSiteManager")
                        .WithMany("ConstructionSites")
                        .HasForeignKey("ConstructionSiteManagerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.Manager", b =>
                {
                    b.HasOne("ConstructionCompanyDataLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.Task", b =>
                {
                    b.HasOne("ConstructionCompanyDataLayer.Models.Worksheet", "Worksheet")
                        .WithMany("Tasks")
                        .HasForeignKey("WorksheetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.UserRole", b =>
                {
                    b.HasOne("ConstructionCompanyDataLayer.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ConstructionCompanyDataLayer.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.Worker", b =>
                {
                    b.HasOne("ConstructionCompanyDataLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.WorkerTask", b =>
                {
                    b.HasOne("ConstructionCompanyDataLayer.Models.Task", "Task")
                        .WithMany("WorkerTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ConstructionCompanyDataLayer.Models.Worker", "Worker")
                        .WithMany("WorkerTasks")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.Worksheet", b =>
                {
                    b.HasOne("ConstructionCompanyDataLayer.Models.ConstructionSite", "ConstructionSite")
                        .WithMany()
                        .HasForeignKey("ConstructionSiteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ConstructionCompanyDataLayer.Models.ConstructionSiteManager", "ConstructionSiteManager")
                        .WithMany("Worksheets")
                        .HasForeignKey("ConstructionSiteManagerId");
                });

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.WorksheetEquipment", b =>
                {
                    b.HasOne("ConstructionCompanyDataLayer.Models.Equipment", "Equipment")
                        .WithMany("WorksheetEquipment")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ConstructionCompanyDataLayer.Models.Worksheet", "Worksheet")
                        .WithMany("WorksheetEquipment")
                        .HasForeignKey("WorksheetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ConstructionCompanyDataLayer.Models.WorksheetMaterial", b =>
                {
                    b.HasOne("ConstructionCompanyDataLayer.Models.Material", "Material")
                        .WithMany("WorksheetMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ConstructionCompanyDataLayer.Models.Worksheet", "Worksheet")
                        .WithMany("WorksheetMaterials")
                        .HasForeignKey("WorksheetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
